package poo.figurasgeometricasfix;

/**
 *
 * @author juanh
 */
public class VentanaPruebaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEjercicio18
     */
    public VentanaPruebaFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        RadioCirculoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AreaCirculoDisplay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PerimetroCirculoDisplay = new javax.swing.JTextField();
        CalcularPerimetroCirculoButton = new javax.swing.JButton();
        BorrarCirculoButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CalcularAreaCirculoButton = new javax.swing.JButton();
        PerimetroCuadradoDisplay = new javax.swing.JTextField();
        CalcularPerimetroCuadradoButton = new javax.swing.JButton();
        BorrarCuadradoButton = new javax.swing.JButton();
        CalcularAreaCuadradoButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LadoCuadradoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AreaCuadradoDisplay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PerimetroRectanguloDisplay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BaseRectanguloField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AreaRectanguloDisplay = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AlturaRectanguloField = new javax.swing.JTextField();
        CalcularAreaRectanguloButton = new javax.swing.JButton();
        CalcularPerimetroRectanguloButton = new javax.swing.JButton();
        BorrarRectanguloButton = new javax.swing.JButton();
        PerimetroTriRectanguloDisplay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BaseTriRectanguloField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AreaTriRectanguloDisplay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AlturaTriRectanguloField = new javax.swing.JTextField();
        CalcularAreaTriRectanguloButton = new javax.swing.JButton();
        CalcularPerimetroTriRectanguloButton = new javax.swing.JButton();
        BorrarTriRectanguloButton = new javax.swing.JButton();
        DeterminarTrianguloButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        DeterminarTrianguloDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Ingrese el Radio");

        RadioCirculoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RadioCirculoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCirculoFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventana Prueba Figuras");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Área");

        AreaCirculoDisplay.setEditable(false);
        AreaCirculoDisplay.setBackground(new java.awt.Color(204, 204, 204));
        AreaCirculoDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AreaCirculoDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCirculoDisplayActionPerformed(evt);
            }
        });

        jLabel5.setText("Perímetro");

        PerimetroCirculoDisplay.setEditable(false);
        PerimetroCirculoDisplay.setBackground(new java.awt.Color(204, 204, 204));
        PerimetroCirculoDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroCirculoDisplayActionPerformed(evt);
            }
        });

        CalcularPerimetroCirculoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularPerimetroCirculoButton.setText("Calcular Perímetro");
        CalcularPerimetroCirculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPerimetroCirculoButtonActionPerformed(evt);
            }
        });

        BorrarCirculoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorrarCirculoButton.setText("Borrar Campos");
        BorrarCirculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCirculoButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Círculo");

        CalcularAreaCirculoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularAreaCirculoButton.setText("Calcular Área");
        CalcularAreaCirculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAreaCirculoButtonActionPerformed(evt);
            }
        });

        PerimetroCuadradoDisplay.setEditable(false);
        PerimetroCuadradoDisplay.setBackground(new java.awt.Color(204, 204, 204));
        PerimetroCuadradoDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroCuadradoDisplayActionPerformed(evt);
            }
        });

        CalcularPerimetroCuadradoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularPerimetroCuadradoButton.setText("Calcular Perímetro");
        CalcularPerimetroCuadradoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPerimetroCuadradoButtonActionPerformed(evt);
            }
        });

        BorrarCuadradoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorrarCuadradoButton.setText("Borrar Campos");
        BorrarCuadradoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCuadradoButtonActionPerformed(evt);
            }
        });

        CalcularAreaCuadradoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularAreaCuadradoButton.setText("Calcular Área");
        CalcularAreaCuadradoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAreaCuadradoButtonActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Ingrese el Lado");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cuadrado");

        LadoCuadradoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LadoCuadradoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LadoCuadradoFieldActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Área");

        AreaCuadradoDisplay.setEditable(false);
        AreaCuadradoDisplay.setBackground(new java.awt.Color(204, 204, 204));
        AreaCuadradoDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AreaCuadradoDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCuadradoDisplayActionPerformed(evt);
            }
        });

        jLabel10.setText("Perímetro");

        PerimetroRectanguloDisplay.setEditable(false);
        PerimetroRectanguloDisplay.setBackground(new java.awt.Color(204, 204, 204));
        PerimetroRectanguloDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroRectanguloDisplayActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Ingrese la Base");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Rectángulo");

        BaseRectanguloField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BaseRectanguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseRectanguloFieldActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Área");

        AreaRectanguloDisplay.setEditable(false);
        AreaRectanguloDisplay.setBackground(new java.awt.Color(204, 204, 204));
        AreaRectanguloDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AreaRectanguloDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaRectanguloDisplayActionPerformed(evt);
            }
        });

        jLabel14.setText("Perímetro");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Ingrese la Altura");

        AlturaRectanguloField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AlturaRectanguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaRectanguloFieldActionPerformed(evt);
            }
        });

        CalcularAreaRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularAreaRectanguloButton.setText("Calcular Área");
        CalcularAreaRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAreaRectanguloButtonActionPerformed(evt);
            }
        });

        CalcularPerimetroRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularPerimetroRectanguloButton.setText("Calcular Perímetro");
        CalcularPerimetroRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPerimetroRectanguloButtonActionPerformed(evt);
            }
        });

        BorrarRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorrarRectanguloButton.setText("Borrar Campos");
        BorrarRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarRectanguloButtonActionPerformed(evt);
            }
        });

        PerimetroTriRectanguloDisplay.setEditable(false);
        PerimetroTriRectanguloDisplay.setBackground(new java.awt.Color(204, 204, 204));
        PerimetroTriRectanguloDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroTriRectanguloDisplayActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Ingrese la Base");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Triángulo Rectángulo");

        BaseTriRectanguloField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BaseTriRectanguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseTriRectanguloFieldActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Área");

        AreaTriRectanguloDisplay.setEditable(false);
        AreaTriRectanguloDisplay.setBackground(new java.awt.Color(204, 204, 204));
        AreaTriRectanguloDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AreaTriRectanguloDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTriRectanguloDisplayActionPerformed(evt);
            }
        });

        jLabel19.setText("Perímetro");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Ingrese la Altura");

        AlturaTriRectanguloField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AlturaTriRectanguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaTriRectanguloFieldActionPerformed(evt);
            }
        });

        CalcularAreaTriRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularAreaTriRectanguloButton.setText("Calcular Área");
        CalcularAreaTriRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAreaTriRectanguloButtonActionPerformed(evt);
            }
        });

        CalcularPerimetroTriRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CalcularPerimetroTriRectanguloButton.setText("Calcular Perímetro");
        CalcularPerimetroTriRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPerimetroTriRectanguloButtonActionPerformed(evt);
            }
        });

        BorrarTriRectanguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorrarTriRectanguloButton.setText("Borrar Campos");
        BorrarTriRectanguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarTriRectanguloButtonActionPerformed(evt);
            }
        });

        DeterminarTrianguloButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeterminarTrianguloButton.setText("Determinar Tipo de Triángulo");
        DeterminarTrianguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminarTrianguloButtonActionPerformed(evt);
            }
        });

        jLabel21.setText("Tipo de Triángulo");

        DeterminarTrianguloDisplay.setEditable(false);
        DeterminarTrianguloDisplay.setBackground(new java.awt.Color(204, 204, 204));
        DeterminarTrianguloDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminarTrianguloDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CalcularAreaCirculoButton)
                            .addGap(4, 4, 4)
                            .addComponent(CalcularPerimetroCirculoButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AreaCirculoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(RadioCirculoField)
                                .addComponent(PerimetroCirculoDisplay, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(BorrarCirculoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel11)
                            .addGap(44, 44, 44)
                            .addComponent(BaseRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BorrarRectanguloButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CalcularAreaRectanguloButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CalcularPerimetroRectanguloButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AreaRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AlturaRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PerimetroRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel16)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DeterminarTrianguloButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BorrarTriRectanguloButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CalcularAreaTriRectanguloButton)
                                            .addGap(4, 4, 4)
                                            .addComponent(CalcularPerimetroTriRectanguloButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AreaTriRectanguloDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(AlturaTriRectanguloField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(PerimetroTriRectanguloDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(DeterminarTrianguloDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(BaseTriRectanguloField)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CalcularAreaCuadradoButton)
                                .addGap(4, 4, 4)
                                .addComponent(CalcularPerimetroCuadradoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AreaCuadradoDisplay)
                                    .addComponent(LadoCuadradoField)
                                    .addComponent(PerimetroCuadradoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BorrarCuadradoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(79, 79, 79))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LadoCuadradoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AreaCuadradoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PerimetroCuadradoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalcularAreaCuadradoButton)
                            .addComponent(CalcularPerimetroCuadradoButton))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(RadioCirculoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AreaCirculoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PerimetroCirculoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalcularAreaCirculoButton)
                            .addComponent(CalcularPerimetroCirculoButton))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BorrarCirculoButton)
                            .addComponent(BorrarCuadradoButton))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(BaseRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(AlturaRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AreaRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PerimetroRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalcularAreaRectanguloButton)
                            .addComponent(CalcularPerimetroRectanguloButton))
                        .addGap(4, 4, 4)
                        .addComponent(BorrarRectanguloButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(BaseTriRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(AlturaTriRectanguloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AreaTriRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PerimetroTriRectanguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeterminarTrianguloDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalcularAreaTriRectanguloButton)
                            .addComponent(CalcularPerimetroTriRectanguloButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeterminarTrianguloButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorrarTriRectanguloButton)))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaCirculoDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaCirculoDisplayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AreaCirculoDisplayActionPerformed

    private void PerimetroCirculoDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroCirculoDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroCirculoDisplayActionPerformed

    private void CalcularPerimetroCirculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPerimetroCirculoButtonActionPerformed
        // TODO add your handling code here:
        
        double perimetro;
        
        int radio = Integer.parseInt(RadioCirculoField.getText());
        
        Circulo figura1 = new Circulo(radio);
        
        perimetro = figura1.calcularPerimetro();
        
        PerimetroCirculoDisplay.setText(String.format("%.5f", perimetro));
        
    }//GEN-LAST:event_CalcularPerimetroCirculoButtonActionPerformed

    private void BorrarCirculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCirculoButtonActionPerformed
        // TODO add your handling code here:
        
        RadioCirculoField.setText("");
        AreaCirculoDisplay.setText("");
        PerimetroCirculoDisplay.setText("");
        
    }//GEN-LAST:event_BorrarCirculoButtonActionPerformed

    private void RadioCirculoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCirculoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCirculoFieldActionPerformed

    private void CalcularAreaCirculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAreaCirculoButtonActionPerformed
        // TODO add your handling code here:
        
        double area;
        
        int radio = Integer.parseInt(RadioCirculoField.getText());
        
        Circulo figura1 = new Circulo(radio);
        
        area = figura1.calcularArea();
        
        AreaCirculoDisplay.setText(String.format("%.5f", area));
    }//GEN-LAST:event_CalcularAreaCirculoButtonActionPerformed

    private void PerimetroCuadradoDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroCuadradoDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroCuadradoDisplayActionPerformed

    private void CalcularPerimetroCuadradoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPerimetroCuadradoButtonActionPerformed
        // TODO add your handling code here:
        
        double perimetro;
        
        int lado = Integer.parseInt(LadoCuadradoField.getText());
        
        Cuadrado figura1 = new Cuadrado(lado);
        
        perimetro = figura1.calcularPerimetro();
        
        PerimetroCuadradoDisplay.setText(String.format("%.5f", perimetro));
    }//GEN-LAST:event_CalcularPerimetroCuadradoButtonActionPerformed

    private void BorrarCuadradoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCuadradoButtonActionPerformed
        // TODO add your handling code here:
        LadoCuadradoField.setText("");
        AreaCuadradoDisplay.setText("");
        PerimetroCuadradoDisplay.setText("");
    }//GEN-LAST:event_BorrarCuadradoButtonActionPerformed

    private void CalcularAreaCuadradoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAreaCuadradoButtonActionPerformed
        // TODO add your handling code here:
        
        double area;
        
        int lado = Integer.parseInt(LadoCuadradoField.getText());
        
        Cuadrado figura1 = new Cuadrado(lado);
        
        area = figura1.calcularArea();
        
        AreaCuadradoDisplay.setText(String.format("%.5f", area));
    }//GEN-LAST:event_CalcularAreaCuadradoButtonActionPerformed

    private void LadoCuadradoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LadoCuadradoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LadoCuadradoFieldActionPerformed

    private void AreaCuadradoDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaCuadradoDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaCuadradoDisplayActionPerformed

    private void PerimetroRectanguloDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroRectanguloDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroRectanguloDisplayActionPerformed

    private void BaseRectanguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseRectanguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseRectanguloFieldActionPerformed

    private void AreaRectanguloDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaRectanguloDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaRectanguloDisplayActionPerformed

    private void AlturaRectanguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaRectanguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaRectanguloFieldActionPerformed

    private void CalcularAreaRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAreaRectanguloButtonActionPerformed
        // TODO add your handling code here:
        double area;
        
        int base = Integer.parseInt(BaseRectanguloField.getText());
        int altura = Integer.parseInt(AlturaRectanguloField.getText());
        
        Rectangulo figura1 = new Rectangulo(base, altura);
        
        area = figura1.calcularArea();
        
        AreaRectanguloDisplay.setText(String.format("%.5f", area));
    }//GEN-LAST:event_CalcularAreaRectanguloButtonActionPerformed

    private void CalcularPerimetroRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPerimetroRectanguloButtonActionPerformed
        // TODO add your handling code here:
        double perimetro;
        
        int base = Integer.parseInt(BaseRectanguloField.getText());
        int altura = Integer.parseInt(AlturaRectanguloField.getText());
        
        Rectangulo figura1 = new Rectangulo(base, altura);
        
        perimetro = figura1.calcularPerimetro();
        
        PerimetroRectanguloDisplay.setText(String.format("%.5f", perimetro));
    }//GEN-LAST:event_CalcularPerimetroRectanguloButtonActionPerformed

    private void BorrarRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarRectanguloButtonActionPerformed
        // TODO add your handling code here:
        BaseRectanguloField.setText("");
        AlturaRectanguloField.setText("");
        PerimetroRectanguloDisplay.setText("");
        AreaRectanguloDisplay.setText("");
    }//GEN-LAST:event_BorrarRectanguloButtonActionPerformed

    private void PerimetroTriRectanguloDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroTriRectanguloDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroTriRectanguloDisplayActionPerformed

    private void BaseTriRectanguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseTriRectanguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseTriRectanguloFieldActionPerformed

    private void AreaTriRectanguloDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTriRectanguloDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTriRectanguloDisplayActionPerformed

    private void AlturaTriRectanguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaTriRectanguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaTriRectanguloFieldActionPerformed

    private void CalcularAreaTriRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAreaTriRectanguloButtonActionPerformed
        // TODO add your handling code here:
        double area;
        
        int base = Integer.parseInt(BaseTriRectanguloField.getText());
        int altura = Integer.parseInt(AlturaTriRectanguloField.getText());
        
        TrianguloRectangulo figura1 = new TrianguloRectangulo(base, altura);
        
        area = figura1.calcularArea();
        
        AreaTriRectanguloDisplay.setText(String.format("%.5f", area));
        
    }//GEN-LAST:event_CalcularAreaTriRectanguloButtonActionPerformed

    private void CalcularPerimetroTriRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPerimetroTriRectanguloButtonActionPerformed
        // TODO add your handling code here:
        double perimetro;
        
        int base = Integer.parseInt(BaseTriRectanguloField.getText());
        int altura = Integer.parseInt(AlturaTriRectanguloField.getText());
        
        TrianguloRectangulo figura1 = new TrianguloRectangulo(base, altura);
        
        perimetro = figura1.calcularPerimetro();
        
        PerimetroTriRectanguloDisplay.setText(String.format("%.5f", perimetro));
    }//GEN-LAST:event_CalcularPerimetroTriRectanguloButtonActionPerformed

    private void BorrarTriRectanguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarTriRectanguloButtonActionPerformed
        // TODO add your handling code here:
        BaseTriRectanguloField.setText("");
        AlturaTriRectanguloField.setText("");
        PerimetroTriRectanguloDisplay.setText("");
        AreaTriRectanguloDisplay.setText("");
        DeterminarTrianguloDisplay.setText("");
    }//GEN-LAST:event_BorrarTriRectanguloButtonActionPerformed

    private void DeterminarTrianguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminarTrianguloButtonActionPerformed
        // TODO add your handling code here:
        
        int base = Integer.parseInt(BaseTriRectanguloField.getText());
        int altura = Integer.parseInt(AlturaTriRectanguloField.getText());
        
        TrianguloRectangulo figura1 = new TrianguloRectangulo(base, altura);
        
        figura1.determinarTipoTriangulo();
        
        DeterminarTrianguloDisplay.setText(figura1.tipodetriangulo);
        
    }//GEN-LAST:event_DeterminarTrianguloButtonActionPerformed

    private void DeterminarTrianguloDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminarTrianguloDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeterminarTrianguloDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPruebaFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaRectanguloField;
    private javax.swing.JTextField AlturaTriRectanguloField;
    private javax.swing.JTextField AreaCirculoDisplay;
    private javax.swing.JTextField AreaCuadradoDisplay;
    private javax.swing.JTextField AreaRectanguloDisplay;
    private javax.swing.JTextField AreaTriRectanguloDisplay;
    private javax.swing.JTextField BaseRectanguloField;
    private javax.swing.JTextField BaseTriRectanguloField;
    private javax.swing.JButton BorrarCirculoButton;
    private javax.swing.JButton BorrarCuadradoButton;
    private javax.swing.JButton BorrarRectanguloButton;
    private javax.swing.JButton BorrarTriRectanguloButton;
    private javax.swing.JButton CalcularAreaCirculoButton;
    private javax.swing.JButton CalcularAreaCuadradoButton;
    private javax.swing.JButton CalcularAreaRectanguloButton;
    private javax.swing.JButton CalcularAreaTriRectanguloButton;
    private javax.swing.JButton CalcularPerimetroCirculoButton;
    private javax.swing.JButton CalcularPerimetroCuadradoButton;
    private javax.swing.JButton CalcularPerimetroRectanguloButton;
    private javax.swing.JButton CalcularPerimetroTriRectanguloButton;
    private javax.swing.JButton DeterminarTrianguloButton;
    private javax.swing.JTextField DeterminarTrianguloDisplay;
    private javax.swing.JTextField LadoCuadradoField;
    private javax.swing.JTextField PerimetroCirculoDisplay;
    private javax.swing.JTextField PerimetroCuadradoDisplay;
    private javax.swing.JTextField PerimetroRectanguloDisplay;
    private javax.swing.JTextField PerimetroTriRectanguloDisplay;
    private javax.swing.JTextField RadioCirculoField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
